#!/usr/bin/env python3
"""Concatenate the cat's ES modules into one classic script.

A WebView will not load ES modules from a file:// URL -- the same CORS rule
that stops it in a desktop browser -- and the overlay Service has no HTTP
server to serve them from. Stripping the import/export syntax and concatenating
in dependency order sidesteps the whole problem.
"""
import re, sys, pathlib

SRC = pathlib.Path(sys.argv[1])
OUT = pathlib.Path(sys.argv[2])
ORDER = ["physics.js", "cat-svg.js", "poses.js", "cat.js"]

parts = ["// GENERATED by tools/bundle-cat.py - do not edit.\n"]
for name in ORDER:
    text = (SRC / name).read_text()
    # Drop import statements; every symbol ends up in one scope anyway.
    text = re.sub(r'^\s*import\s+[^;]+;\s*$', '', text, flags=re.M)
    # `export class X` -> `class X`, `export const X` -> `const X`
    text = re.sub(r'^\s*export\s+(?=(class|const|function|let|var)\b)', '', text, flags=re.M)
    parts.append(f"\n// ---- {name} ----\n{text}\n")

OUT.write_text("".join(parts))
bad = [l for l in OUT.read_text().splitlines() if re.match(r'\s*(import|export)\s', l)]
if bad:
    print("LEFTOVER MODULE SYNTAX:", bad[:3]); sys.exit(1)
print(f"bundled {len(ORDER)} files -> {OUT} ({OUT.stat().st_size//1024}KB)")
